#[[main]]
#  name = "Home"
#  identifier = "home"
#  url = "/"
#  pre = "<i class='fa fa-home'></i>"
#  post = "<span>News !</span>"
#  weight = 1
#  [[main]]
#    name = "A propos"
#    identifier = "propos"
#    parent = "hacf"
#    url = "/a-propos"
#    weight = 1
#  [[main]]
#    name = "Contribuer"
#    identifier = "contribuer"
#    parent = "hacf"
#    url = "/contribuer"
#    weight = 2

[[main]]
  name = "Accueil"
  identifier = "home"
  url = "/"
  pre = ""
  post = ""
  weight = 1
[[main]]
  name = "Actualités"
  identifier = "news"
  url = "/news"
  pre = ""
  weight = 2
[[main]]
  name = "Articles"
  identifier = "post"
  url = "/blog"
  pre = ""
  weight = 3
[[main]]
  name = "Association"
  identifier = "association"
  url = "/pages/association"
  pre = ""
  weight = 4
[[main]]
  name = "Liens Utiles"
  identifier = "awesome"
  url = "/pages/awesome"
  pre = ""
  weight = 5
#[[main]]
#  name = "Nos Médias"
#  identifier = "medias"
#  url = "/pages/medias"
#  weight = 6

[[footer]]
name = "A propos"
url = "/pages/about"
[[footer]]
name = "Protection des données"
url = "/protection-des-donnees"
[[footer]]
name = "Nous-contacter"
url = "/contact"


[[hacf]]
name = "Email"
url = "https://contact.hacf.fr"
pre = 'fa-envelope'
weight = 1
[[hacf]]
name = "Forum"
url = "https://forum.hacf.fr"
pre = 'fa-discourse'
weight = 2
[[hacf]]
name = "Discord"
url = "https://discord.hacf.fr"
pre = 'fa-discord'
weight = 3
[[hacf]]
name = "Groupe Facebook"
url = "https://groupe-facebook.hacf.fr"
pre = 'fa-facebook-messenger'
weight = 4
[[hacf]]
name = "GitHub"
url = "https://github.hacf.fr"
pre = 'fa-github'
weight = 5
[[hacf]]
name = "YouTube"
url = "https://youtube.hacf.fr"
pre = 'fa-youtube'
weight = 6
[[hacf]]
name = "Twitter"
url = "https://twitter.hacf.fr"
pre = 'fa-twitter'
weight = 7
[[hacf]]
name = "Facebook"
url = "https://facebook.hacf.fr"
pre = 'fa-facebook'
weight = 8

[[haoff]]
name = "Site Web"
url = "https://www.home-assistant.io/"
pre = 'fa-home'
weight = 1
[[haoff]]
name = "Discourse"
url = "https://community.home-assistant.io/"
pre = 'fa-discourse'
weight = 2
[[haoff]]
name = "Discord"
url = "https://discord.com/invite/c5DvZ4e"
pre = 'fa-discord'
weight = 3
[[haoff]]
name = "Github"
url = "https://github.com/home-assistant/"
pre = 'fa-github'
weight = 6
[[haoff]]
name = "Facebook Group"
url = "https://www.facebook.com/groups/HomeAssistant/"
pre = 'fa-facebook'
weight = 4
[[haoff]]
name = "Reddit"
url = "https://www.reddit.com/r/homeassistant/"
pre = 'fareddit'
weight = 5
[[haoff]]
name = "Twitter"
url = "https://twitter.com/home_assistant"
pre = 'fa-twitter'
weight = 7
[[haoff]]
name = "Facebook"
url = "https://www.facebook.com/homeassistantio"
pre = 'fa-facebook'
weight = 8


[[aidehacf]]
name = "Discourse"
url = "https://forum.hacf.fr"
pre = 'fa-discourse'
weight = 1
[[aidehacf]]
name = "Discord"
url = "http://discord.hacf.fr"
pre = 'fa-discord'
weight = 2
[[aidehacf]]
name = "Facebook Group"
url = "http://groupe-facebook.hacf.fr"
pre = 'fa-facebook'
weight = 3

[[aidehaoff]]
name = "Discourse"
url = "https://community.home-assistant.io/"
pre = 'fa-discourse'
weight = 1
[[aidehaoff]]
name = "Discord"
url = "https://discord.com/invite/c5DvZ4e"
pre = 'fa-discord'
weight = 2
[[aidehaoff]]
name = "Reddit"
url = "https://www.reddit.com/r/homeassistant/"
pre = 'fa-reddit'
weight = 3
[[aidehaoff]]
name = "Facebook Group"
url = "https://www.facebook.com/groups/HomeAssistant/"
pre = 'fa-facebook'
weight = 4
