[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.112.7"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

NODE_VERSION = "18.16.0"
NPM_VERSION = "9.5.1"

[context.deploy-preview]
command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"
