[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.112.7"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

NETLIFY_USE_YARN = "true"
YARN_VERSION = "1.22.17"

[context.deploy-preview]
command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"
