backend:
  name: git-gateway
  branch: postpub # Branch to update (optional; defaults to master)
  site_domain: https://bright-hummingbird-cf02c5.netlify.app/
  
local_backend: true

# Permet l'activtion d'un flux de travail (brouillon, a relire, a publier)
# Peut etre desactivé en commantant la ligne ci-dessous.
## ATTENTION non disponible en local.
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Chemin ou sont stocké les medias uploadés, dans Hugo par defaut c'est static/images/uploads ou assets/images/uploads pour pouvoir utiliser le resize.image.
public_folder: "/images/uploads" # Chemin de vos images une fois le site publié /images/uploads

collections:
# Article en 1 fichier
#  - name: "blog" # Used in routes, e.g., /admin/collections/blog
#    label: "Blog" # Used in the UI
#    folder: "content/blog" # Chemin du dossier contenant les articles de blog.
#    create: true # Autoriser les utilisateur a créer du contenus dans cette collection.
#    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

## Articles en dossier
#  - name: "blog2" # Used in routes, e.g., /admin/collections/post
#    label: "Blog avec Dossier" # Used in the UI
#    folder: "content/posts" # The path to the folder where the documents are stored
#    path: "{{slug}}/index"
#    media_folder: "" # Save images in the post's own folder instead of the static folder
#    public_folder: ""

# Articles avec dossier img
  - name: "blog" # Used in routes, e.g., /admin/collections/post
    #layout: blog  # Si layout personalisé
    label: "Articles / Tutoriels" # Used in the UI
    label_singular: 'article' # Used in the UI, ie: "New Post"
    description: >
      Ajouter un article a la communauté.
    folder: "content/blog" # Dossier ou sont stocké les articles
    path: "{{slug}}/index" #nom du fichier .md contenant l'article NE PAS MODIFIER
    #summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    media_folder: "img/" # Endroit ou sont stocké les images de l'article
    public_folder: "img/"
    create: true # Autoriser les utilisateurs a créer du contenus dans cette collection.
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Brouillon
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: 
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: false }
      - {
          label: 'Date de publication',
          name: 'date',
          widget: 'datetime',
          date_format: 'DD-MM-YY',
          time_format: 'HH:mm',
          format: 'DD-MM-YY HH:mm',
        }
      - {
          label: 'Date de modification',
          name: 'lastmod',
          widget: 'datetime',
          date_format: 'DD-MM-YY',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text",  hint: "Description devant faire entre x et xx caracteres "}
      - { label: "Partager sur les réseaux sociaux", name: "socialshare", widget: "boolean", default: true }
      - {
          label: 'Categorie(s)',
          name: 'categories',
          widget: 'select',
          multiple: true,
          min: 1,
          options: ['Installation','Add-on','Intégration', 'Automatisation', 'ESPHome', 'Do It Yourself'],
        }
      - {
          label: 'Série(s)',
          name: 'series',
          widget: 'select',
          multiple: true,
          min: 1,
          options: ['HA les Bases','Débuter avec Home Assistant'],
        }
      - label: "Auteur(s)"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["title"]
        valueField: "title"
        multiple: true
        hint: "Vous pouvez creer votre auteur et venir le modifier plus tard"

      - { label: "Body", name: "body", widget: "markdown" }
      
# Modifier page index et About
  - name: "pages"
    label: "Pages"
    create: false
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }

# Add author
  - name: "authors"
    label: "Ajouter un Auteur"
    extension: "json"
    format: "json"
    folder: "data/authors"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Pseudos", name: "title", widget: "string" }
      - { label: "Fonction", name: "fonction", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Réseaux Sociaux",
          name: "social_network",
          widget: "object",
          fields:
            [
              { label: "Profil Facebook", name: "facebook", widget: "string" },
              { label: "Profil Twitter", name: "twitter", widget: "string" }
            ]
        }