backend:
  name: git-gateway
  branch: postpub # Branch to update (optional; defaults to master)
  site_domain: https://bright-hummingbird-cf02c5.netlify.app/
  
local_backend: true

# Permet l'activtion d'un flux de travail (brouillon, a relire, a publier)
# Peut etre desactivé en commantant la ligne ci-dessous.
## ATTENTION non disponible en local.
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Chemin ou sont stocké les medias uploadés, dans Hugo par defaut c'est static/images/uploads ou assets/images/uploads pour pouvoir utiliser le resize.image.
public_folder: "/images/uploads" # Chemin de vos images une fois le site publié /images/uploads

collections:
# Article en 1 fichier
#  - name: "blog" # Used in routes, e.g., /admin/collections/blog
#    label: "Blog" # Used in the UI
#    folder: "content/blog" # Chemin du dossier contenant les articles de blog.
#    create: true # Autoriser les utilisateur a créer du contenus dans cette collection.
#    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

## Articles en dossier
#  - name: "blog2" # Used in routes, e.g., /admin/collections/post
#    label: "Blog avec Dossier" # Used in the UI
#    folder: "content/posts" # The path to the folder where the documents are stored
#    path: "{{slug}}/index"
#    media_folder: "" # Save images in the post's own folder instead of the static folder
#    public_folder: ""

###############################################
###############################################
# COLLECTION ARTICLE BLOG
###############################################
###############################################
  - name: "blog" # Used in routes, e.g., /admin/collections/post
    #layout: blog  # Si layout personalisé
    label: "Articles / Tutoriels" # Used in the UI
    label_singular: 'article' # Used in the UI, ie: "New Post"
    description: >
      Ajouter un article a la communauté.
    folder: "content/blog" # Dossier ou sont stocké les articles
    path: "{{slug}}/index" #nom du fichier .md contenant l'article NE PAS MODIFIER
    #summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    media_folder: "img/" # Endroit ou sont stocké les images de l'article
    public_folder: "img/"
    create: true # Autoriser les utilisateurs a créer du contenus dans cette collection.
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Brouillon
        field: draft
        pattern: true
    view_groups:
      - label: Par années
        field: date
        pattern: \d{4}
      - label: Brouillons
        field: draft
      - label: Catégories
        field: categories
    fields: 
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Date de publication',
          name: 'date',
          widget: 'datetime',
          date_format: 'DD-MM-YY',
          time_format: 'HH:mm',
          format: 'DD-MM-YY HH:mm',
        }
      - {
          label: 'Date de modification',
          name: 'lastmod',
          widget: 'datetime',
          date_format: 'DD-MM-YY',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
          required: false
        }
      - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Laisser vide pour prendre celle pr defaut. Sinon, votre image doit être au format .jpg, .gif, .png, webp, vous pouvez prendre l'image vierge a habiller https://cloud.hacf.fr/s/bAsnN3S5StCHG55" }
      - { label: "Description", name: "description", widget: "text",  hint: "Description devant faire entre x et xx caracteres "}
      - { label: "Partager sur les réseaux sociaux", name: "socialshare", widget: "boolean", default: true }
      - {
          label: 'Categorie(s)',
          name: 'categories',
          widget: 'select',
          multiple: true,
          min: 1,
          options: ['Installation','Add-on','Intégration', 'Automatisation', 'ESPHome', 'Do It Yourself'],
        }

      - {
        label: "Tags",
        name: "tags",
        widget: "list",
        allow_add: true,
        hint: Séparer vos tags par une virgule
        }     

      - {
          label: 'Série(s)',
          name: 'series',
          widget: 'select',
          multiple: true,
          min: 1,
          options: ['HA les Bases','Débuter avec Home Assistant'],
        }
      - label: "Auteur(s)"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["title"]
        valueField: "title"
        required: false
        multiple: true
        hint: "Vous pouvez creer votre auteur et venir le modifier plus tard"

      - {label: "Liens vers sujet du forum", name: "url_hacf", widget: "string", required: false }
      - {label: "Liens vers sujet du forum", name: "url_haoff", widget: "string", required: false }

      - { label: "Body", name: "body", widget: "markdown" }

    
###############################################
###############################################
# COLLECTION NEWS
###############################################
###############################################

  - name: "news" # Used in routes, e.g., /admin/collections/post
    #layout: blog  # Si layout personalisé
    label: "Actualités" # Used in the UI
    label_singular: 'article' # Used in the UI, ie: "New Post"
    description: >
      Ajouter une actualité domotique ou sur Home Assistant.
    folder: "content/news" # Dossier ou sont stocké les articles
    path: "{{slug}}/index" #nom du fichier .md contenant l'article NE PAS MODIFIER
    #summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    media_folder: "img/" # Endroit ou sont stocké les images de l'article
    public_folder: "img/"
    create: true # Autoriser les utilisateurs a créer du contenus dans cette collection.
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Brouillon
        field: draft
        pattern: true
    view_groups:
      - label: Par années
        field: date
        pattern: \d{4}
      - label: Brouillons
        field: draft
      - label: Catégories
        field: categories
    fields: 
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Date de publication',
          name: 'date',
          widget: 'datetime',
          date_format: 'DD-MM-YY',
          time_format: 'HH:mm',
          format: 'DD-MM-YY HH:mm',
        }
      - {
          label: 'Date de modification',
          name: 'lastmod',
          widget: 'datetime',
          date_format: 'DD-MM-YY',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
          required: false
        }
      - { label: "Featured Image", name: "image", widget: "image", required: false, choose_url: true, hint: "Laisser vide pour prendre celle pr defaut. Sinon, votre image doit être au format .jpg, .gif, .png, webp, vous pouvez prendre l'image vierge a habiller https://cloud.hacf.fr/s/bAsnN3S5StCHG55" }
      - { label: "Description", name: "description", widget: "text",  hint: "Description devant faire entre x et xx caracteres "}
      - { label: "Partager sur les réseaux sociaux", name: "socialshare", widget: "boolean", default: true }
      - {label: "Catégories", name: "categories", widget: "hidden", default: "actualités"}

      - {
        label: "Tags",
        name: "tags",
        widget: "list",
        allow_add: true,
        hint: Séparer vos tags par une virgule
        }     

      - label: "Auteur(s)"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["title"]
        valueField: "title"
        required: false
        multiple: true
        hint: "Vous pouvez creer votre auteur et venir le modifier plus tard"

      - {label: "Lien vers sujet du forum Francophone", name: "url_hacf", widget: "string", required: false }
      - {label: "Lien vers sujet du forum Officiel", name: "url_haoff", widget: "string", required: false }

      - { label: "Body", name: "body", widget: "markdown" }

      
###############################################

# COLLECTION PAGES

###############################################
  - name: "pages"
    #layout: blog  # Si layout personalisé
    label: "Pages"
    label_singular: 'page' # Used in the UI, ie: "New Post"
    create: false
    media_folder: "img/" # Endroit ou sont stocké les images de l'article
    public_folder: "img/"
    files:
      - file: "content/pages/awesome/index.md"
        label: "Liens utiles"
        name: "awesome"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: false }
          - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Laisser vide pour prendre celle pr defaut. Sinon, votre image doit être au format .jpg, .gif, .png, webp, vous pouvez prendre l'image vierge a habiller https://cloud.hacf.fr/s/bAsnN3S5StCHG55" }
          - { label: "Description", name: "description", widget: "text",  hint: "Description devant faire entre x et xx caracteres "}
          - { label: "Partager sur les réseaux sociaux", name: "socialshare", widget: "boolean", default: true }
          - {
              label: 'Date de modification',
              name: 'lastmod',
              widget: 'datetime',
              date_format: 'DD-MM-YY',
              time_format: 'HH:mm',
              format: 'YYYY-MM-DD HH:mm',
              required: false
            }
          - {
            label: "Tags",
            name: "tags",
            widget: "list",
            allow_add: true,
            hint: Séparer vos tags par une virgule
            }
          
          - { label: "Body", name: "body", widget: "markdown" }

          - label: 'Liens utiles'
            name: 'liens_utiles'
            widget: 'list'
            fields:
              - {label: "Nom", name: "title", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {
                  label: "Logo",
                  name: "logo",
                  widget: "image",
                  choose_url: false,
                  media_folder: "img",
                  public_folder: "img",
                  default: "images/author/hacf.webp",
                  media_library:
                    [
                    config:
                      [
                        multiple: false
                      ]  
                    ]
                    
                }
              - {
                  label: "Type de contenu",
                  name: "type",
                  widget: "select",
                  multiple: true,
                  options: ["blog", "videos", "podcast", "documentations", "diy", "autres"]
                }

                      

      - file: "content/pages/association/index.md"
        label: "Association"
        name: "association"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: false }
          - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Laisser vide pour prendre celle pr defaut. Sinon, votre image doit être au format .jpg, .gif, .png, webp, vous pouvez prendre l'image vierge a habiller https://cloud.hacf.fr/s/bAsnN3S5StCHG55" }
          - { label: "Description", name: "description", widget: "text",  hint: "Description devant faire entre x et xx caracteres "}
          - { label: "Partager sur les réseaux sociaux", name: "socialshare", widget: "boolean", default: true }
          - {
              label: 'Date de modification',
              name: 'lastmod',
              widget: 'datetime',
              date_format: 'DD-MM-YY',
              time_format: 'HH:mm',
              format: 'YYYY-MM-DD HH:mm',
              required: false
            }

          - {
            label: "Tags",
            name: "tags",
            widget: "list",
            allow_add: true,
            hint: Séparer vos tags par une virgule
            }

          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/pages/reglement/index.md"
        label: "Réglement Association"
        name: "reglement"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: false }
          - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Laisser vide pour prendre celle pr defaut. Sinon, votre image doit être au format .jpg, .gif, .png, webp, vous pouvez prendre l'image vierge a habiller https://cloud.hacf.fr/s/bAsnN3S5StCHG55" }
          - { label: "Description", name: "description", widget: "text",  hint: "Description devant faire entre x et xx caracteres "}
          - { label: "Partager sur les réseaux sociaux", name: "socialshare", widget: "boolean", default: true }
          - {
              label: 'Date de modification',
              name: 'lastmod',
              widget: 'datetime',
              date_format: 'DD-MM-YY',
              time_format: 'HH:mm',
              format: 'YYYY-MM-DD HH:mm',
              required: false
            }

          - {
            label: "Tags",
            name: "tags",
            widget: "list",
            allow_add: true,
            hint: Séparer vos tags par une virgule
            }

          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/pages/statuts/index.md"
        label: "Statuts de l'association"
        name: "statuts"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: false }
          - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Laisser vide pour prendre celle pr defaut. Sinon, votre image doit être au format .jpg, .gif, .png, webp, vous pouvez prendre l'image vierge a habiller https://cloud.hacf.fr/s/bAsnN3S5StCHG55" }
          - { label: "Description", name: "description", widget: "text",  hint: "Description devant faire entre x et xx caracteres "}
          - { label: "Partager sur les réseaux sociaux", name: "socialshare", widget: "boolean", default: true }
          - {
              label: 'Date de modification',
              name: 'lastmod',
              widget: 'datetime',
              date_format: 'DD-MM-YY',
              time_format: 'HH:mm',
              format: 'YYYY-MM-DD HH:mm',
              required: false
            }

          - {
            label: "Tags",
            name: "tags",
            widget: "list",
            allow_add: true,
            hint: Séparer vos tags par une virgule
            }

          - { label: "Body", name: "body", widget: "markdown" }

# Add author
  - name: "authors"
    label: "Ajouter un Auteur"
    extension: "json"
    format: "json"
    folder: "data/authors"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Pseudos", name: "title", widget: "string" }
      - { label: "Fonction", name: "fonction", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - {
          label: "Avatar",
          name: "avatar",
          widget: "image",
          choose_url: false,
          media_folder: "/static/images/author",
          public_folder: "images/author",
          default: "images/author/hacf.webp",
          media_library:
            [
            config:
              [
                multiple: false
              ]  
            ]
        }
      - {
          label: "Réseaux Sociaux",
          name: "social_network",
          widget: "object",
          fields:
            [
              { label: "Profil Facebook", name: "facebook", widget: "string", required: false },
              { label: "Profil Twitter", name: "twitter", widget: "string", required: false }
            ]
        }
# ARCHIVE pour les sections du dossier data
#          - {
#              label: "Section",
#              name: "section",
#              widget: "object",
#              fields:
#                [
#                  { label: "Heading", name: "heading", widget: string },
#                  { label: "Text", name: "text", widget: "text" },
#                ],
#            }