backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)
  repo:  hacf-fr/blog_hacf 
  site_domain: https://hacf.fr
#  site_domain: https://hacf.netlify.app/

local_backend: true
#  allowed_hosts: ['localhost']

# Permet l'activtion d'un flux de travail (brouillon, a relire, a publier)
# Peut etre desactivé en commantant la ligne ci-dessous.
## ATTENTION non disponible en local.
#publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Chemin ou sont stocké les medias uploadés, dans Hugo par defaut c'est static/images/uploads ou assets/images/uploads pour pouvoir utiliser le resize.image.
public_folder: "/images/uploads" # Chemin de vos images une fois le site publié /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: blog
    label: Articles / Tutoriels
    label_singular: Blog
    folder: content/blog
    media_folder: 'img' # Endroit ou sont stocké les images de l'article
    public_folder: 'img'
    create: true # Autoriser les utilisateurs a créer du contenus dans cette collection.
    nested:
      depth: 100
      summary: '{{title}}'
      path: { label: 'Path', index_file: 'index' }

    fields:
      - label: Dossier
        name: folder
        widget: string
        required: true
        hint: "Nommage du dossier (non visible), simple, court et sans accents (ex: ha_integration,esphome_introduction ou ha_acces_exterieur_nginx_proxy_manager etc)"
      - label: Titre
        name: title
        widget: string
        required: true

      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {name: visibleInCMS, widget: hidden, default: true }

      - label: "Brouillon"
        name: "draft"
        widget: "boolean"
        default: true
        requiered: false

      - label: "Alias"
        name: "aliases"
        widget: list
        allow_add: true
        required: false
        hint: "Permet d'ajouter des url redirigeant vers cette page. Séparer vos tags par une virgule ex alias /mon-alias"
        summary: '{{fiels.alias}}'
        fields:
          - name: alias
            label: Alias
            widget: string

      - name: 'date'
        label: 'Date de publication'
        widget: 'datetime'
        date_format: 'dd.MM.yyyy' # e.g. 24.12.2022
        time_format: false
        format: 'yyyy-MM-dd' # e.g. 2022-12-24

      - name: 'lastmod'
        label: 'Date de modification'
        widget: 'datetime'
        date_format: 'dd.MM.yyyy' # e.g. 24.12.2022
        time_format: false
        format: 'yyyy-MM-dd' # e.g. 2022-12-24

      - label: Image de l'article
        name: images
        widget: image
        required: false
        hint: "Laisser vide pour prendre celle pr defaut. Sinon, votre image doit être au format .jpg, .gif, .png, webp" 

      - name: description
        label: Description
        widget: text

      - name: level
        label: Niveau
        widget: select
        requiered: false
        options:
          - label: Débutant
            value: beginner
          - label: Intermédiaire
            value: medium
          - label: Avancé
            value: advanced

      - name: type_install
        label: Type d'installation
        widget: select
        requiered: false
        options:
          - label: HA OS
            value: ha-os
          - label: HA Conteneur
            value: ha-container
          - label: HA Core
            value: ha-core

      - label: "Version Home Assistant" 
        name: "version_ha"
        widget: "string" 
        required: false
        hint: "ex: 2024.4.0"

      - name: 'categories'
        label: 'Categorie(s)'
        widget: 'select'
        multiple: true
        options:
          - Add-on/Intégration
          - Automatisation
          - Concepts
          - Confort
          - Développement
          - Energie
          - ESPHome/DIY
          - Installation
          - Interface UI
          - Matériel
          - Node-red
          - Protocoles
          - Réseau
          - Sécurité

      - name: author
        label: Auteur principal
        widget: relation
        collection: authors
        search_fields: ['pseudos']
        value_field: title
        display_fields: ['pseudos']

      - label: "Liens vers sujet du forum HACF (FR)"
        name: url_hacf
        widget: string
        required: false
      - label: "Liens vers sujet du forum Officiel (EN)"
        name: url_haoff
        widget: string
        required: false

      - label: Body
        name: body
        widget: markdown


###############################################################################
#                      Add author
###############################################################################
  - name: authors
    label: Les auteurs
    label_singular: auteur
    folder: data/authors
    extension: json
    format: json
    identifier_field: pseudos
    create: true # Autoriser les utilisateurs a créer du contenus dans cette collection.
    fields:
      - label: "Id"
        name: "title"
        widget: "string"
        hint: "pseudos en minisucule et sans espace"
      - label: Pseudos
        name: pseudos
        widget: string
      - label: Fonction
        name: fonction
        widget: string
      - label: Bio
        name: bio
        widget: text
      - label: Avatar
        name: avatar
        widget: image
        choose_url: false
        media_folder: "/static/images/author"
        public_folder: "images/author"
        default: "images/author/hacf.webp"

      - label: Réseaux Sociaux
        name: social_network
        widget: object
        fields:
          - label: Profil Facebook
            name: facebook
            widget: string
            required: false
          - label: Profil Twitter
            name: twitter
            widget: string
            required: false

      - label: Pseudos sur le forum HACF
        name: pseudo_hacf
        widget: string
        hint: "Mettre seulement le pseudos en minuscule" 
        required: false
      - label: Pseudos sur le forum HA Officiel
        name: pseudo_haoff
        widget: string
        hint: "Mettre seulement le pseudos en minuscule"   
        required: false  